[package]
name = "barcoders"
version = "0.8.2"
authors = ["Andrew Buntine <info@bunts.io>"]
description = "A barcode-encoding library"
homepage = "https://github.com/buntine/barcoders"
repository = "https://github.com/buntine/barcoders"
documentation = "https://docs.rs/barcoders"
readme = "README.md"
keywords = ["barcode", "barcodes", "barcode-encoding"]
license = "MIT OR Apache-2.0"
exclude = [
    "media/*",
]

[features]
ascii = []
json = []
svg = []
dev = ["clippy"]

[dependencies]
image = {version = "0.15.0", optional = true}
clippy = {version = "0.0.134", optional = true}
