[package]
name = "barcoders"
version = "0.3.5"
authors = ["Andrew Buntine <info@bunts.io>"]
description = "A barcode-encoding library"
homepage = "https://github.com/buntine/barcoders"
repository = "https://github.com/buntine/barcoders"
documentation = "http://buntine.github.io/barcoders/barcoders/index.html"
readme = "README.md"
keywords = ["barcode", "barcodes", "barcode-encoding"]
license = "MIT"
exclude = [
    "media/*",
]

[features]
ascii = []
svg = []
dev = ["clippy"]

[dependencies]
image = {version = "0.6.0", optional = true}
clippy = {version = "0.0.35", optional = true}
